
TOPDIR = ..

HOST_TARGET = pnmtohex

# -I/home/tom/65/builds/pure2/release/dreamone/tmp/work/dreamone-oe-linux/fbtest/0.1-r0/recipe-sysroot/usr/include/libnetpbm 
#CFLAGS += -I${STAGING_INCDIR}/libnetpbm 

## Modern distro's (e.g. Debian, Fedora Core) seem to have -lnetpbm only
##LIBS += -lnetpnm -lnetpbm -lnetpgm -lnetppm
#LIBS += -L${STAGING_LIBDIR}/libnetpbm -lnetpbm

include $(TOPDIR)/Rules.make

